runtime: go
api_version: go1

# Let's enable this when we're done with porting
# default_expiration: "180d 0h"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  # secure: always
  http_headers:
    X-Content-Type-Options: nosniff

- url: /static
  static_dir: static
  # secure: always
  http_headers:
    X-Content-Type-Options: nosniff
    Vary: Accept-Encoding

- url: /pastebin/static
  static_dir: pastebin/static
  # secure: always
  http_headers:
    X-Content-Type-Options: nosniff
    Vary: Accept-Encoding

- url: /.*
  # secure: always
  script: _go_app
