webapp:
  CSRFAuthKey: 'u<:>ZoTv3d<45!Bn?ionCt4*4&t;SpV;'
  CSRFSecureC: false # keep this 'false' for local development
  EncryptionK: '&y"c5B[YnZpV.$dFfCu53ij/Dya[Bu?L'
  StaticDomain: "localhost:2019"
  ListenPort: 2019

google:
  GCPOAuthCID: 'GCP Console > API Manager > Credentials > OAuth Client ID > Download JSON'

github:
  clientid: "Paste your GitHub ClientID here"
  clientsecret: "Paste your GitHub Client Secret here"

discord:
  clientid: "Paste your Discord ClientID here"
  clientsecret: "Paste your Discord Client Secret here"

recaptcha:
  key: 'Paste your ReCaptcha v3 Site Key here'
  secret: 'Paste your ReCaptcha v3 Secret Key here'

database:
  connection: "user=ada password=ada dbname=ada-bot sslmode=disable"
  redis: "localhost:6379"

cloudflare:
  token: "Paste your CF API Token here"
  zoneid: "Paste your CF ZoneID here"
  domain: "Paste your CF Domain here"
  schema: "https"
  pageurl: "/pastebinc/%s/content"
  purgeapi: "https://api.cloudflare.com/client/v4/zones/%s/purge_cache"

adayoung: "-my userID goes here!-"
